#!/bin/bash
set -e

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       Astradial — Quick Setup            ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "Docker is required. Install: https://docker.com"; exit 1; }

# ── Admin credentials ──
echo "Set up your admin account:"
read -p "  Email [admin@example.com]: " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
read -p "  Password [admin]: " ADMIN_PASSWORD
ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
read -p "  Name [Admin]: " ADMIN_NAME
ADMIN_NAME=${ADMIN_NAME:-Admin}
echo ""

# ── Platform detection ──
echo "Are you running on a Linux server or VPS? (y/n)"
echo ""
echo "  y = Linux/VPS — full setup with Asterisk PBX"
echo "  n = Mac/Windows — uses Astradial Cloud for calls"
echo ""
read -p "  Linux/VPS? [n]: " IS_LINUX
IS_LINUX=${IS_LINUX:-n}

if [ "$IS_LINUX" = "y" ] || [ "$IS_LINUX" = "Y" ]; then
  MODE="full"
  SIP_HOST=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 2>/dev/null | awk '{print $7;exit}' || echo "localhost")
  SIP_PORT="5060"
  AMI_HOST="asterisk"
  echo ""
  echo "  ✓ Full setup — Asterisk will run in Docker"
  echo "  ✓ SIP server: ${SIP_HOST}:${SIP_PORT}"
else
  MODE="cloud"
  echo ""
  echo "Enter your Asterisk server details:"
  echo "(Email cats@astradial.com if you don't have one)"
  echo ""
  read -p "  Server hostname [stagesip.astradial.com]: " SIP_HOST
  SIP_HOST=${SIP_HOST:-stagesip.astradial.com}
  read -p "  SIP port [5080]: " SIP_PORT
  SIP_PORT=${SIP_PORT:-5080}
  read -p "  SSH user [root]: " SSH_USER
  SSH_USER=${SSH_USER:-root}
  read -p "  Asterisk config path [/etc/asterisk]: " AST_CONFIG_PATH
  AST_CONFIG_PATH=${AST_CONFIG_PATH:-/etc/asterisk}
  read -p "  AMI password [astradial]: " AMI_SECRET
  AMI_SECRET=${AMI_SECRET:-astradial}

  AMI_HOST="$SIP_HOST"

  # Test SSH connection
  echo ""
  echo "  Testing SSH connection to ${SIP_HOST}..."
  if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ${SSH_USER}@${SIP_HOST} "echo ok" >/dev/null 2>&1; then
    echo "  ✓ SSH connection works"
  else
    echo "  ⚠ SSH connection failed. Config deploy won't work."
    echo "  Make sure your SSH key is set up: ssh-copy-id ${SSH_USER}@${SIP_HOST}"
  fi
fi

echo ""

# ── Write .env ──
cat > .env << EOF
# Generated by setup.sh — $(date)
ASTRADIAL_MODE=selfhosted

# Database
DB_NAME=astradial
DB_USER=astradial
DB_PASSWORD=changeme
DB_ROOT_PASSWORD=changeme

# Security
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "change-this-secret")
INTERNAL_API_KEY=$(openssl rand -hex 16 2>/dev/null || echo "change-this-key")

# Admin account (login at http://localhost:3001)
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}
ADMIN_USERNAME=admin
ADMIN_API_PASSWORD=${ADMIN_PASSWORD}

# Asterisk connection
AMI_HOST=${AMI_HOST}
ASTERISK_AMI_SECRET=${AMI_SECRET:-astradial}

# SIP server (shown in softphone credentials)
SIP_HOST=${SIP_HOST}
SIP_PORT=${SIP_PORT}

# Remote config deploy (cloud mode only)
ASTERISK_SSH_HOST=${SIP_HOST}
ASTERISK_SSH_USER=${SSH_USER:-}
ASTERISK_PJSIP_CONFIG_PATH=${AST_CONFIG_PATH:-/etc/asterisk}
EOF

# ── Build ──
echo "[1/5] Building Docker images... (first run takes 3-5 minutes)"
docker compose build 2>&1 | while IFS= read -r line; do
  if echo "$line" | grep -q " Built"; then
    service=$(echo "$line" | sed 's/ Built//')
    echo "  ✓ ${service} built"
  fi
done
echo "  ✓ All images built"

# ── Start database ──
echo "[2/5] Starting database..."
docker compose up -d mariadb redis 2>&1 >/dev/null
for i in $(seq 1 30); do
  if docker compose exec mariadb mariadb -u astradial -pchangeme -e "SELECT 1" >/dev/null 2>&1; then
    break
  fi
  printf "\r  ⏳ Waiting for database... (%s/30)" "$i"
  sleep 2
done
echo ""
echo "  ✓ Database ready"

# ── Asterisk ──
if [ "$MODE" = "full" ]; then
  echo "[3/5] Starting Asterisk PBX..."
  docker compose up -d asterisk 2>&1 >/dev/null
  sleep 3
  echo "  ✓ Asterisk started"
else
  echo "[3/5] Skipping local Asterisk (using Astradial Cloud)"
fi

# ── API + Editor ──
echo "[4/5] Starting API and Dashboard..."
docker compose up -d api editor workflow-engine 2>&1 >/dev/null

for i in $(seq 1 30); do
  if curl -s http://localhost:8000/health >/dev/null 2>&1; then
    echo "  ✓ API is ready"
    break
  fi
  printf "\r  ⏳ Starting API... (%s/30)" "$i"
  sleep 2
done
echo ""

echo "[5/5] Finishing setup..."
for i in $(seq 1 15); do
  if curl -s http://localhost:3001 >/dev/null 2>&1; then
    echo "  ✓ Dashboard is ready"
    break
  fi
  sleep 2
done

# Deploy config (full mode only)
if [ "$MODE" = "full" ]; then
  TOKEN=$(curl -s -X POST http://localhost:8000/api/v1/auth/user-login \
    -H 'Content-Type: application/json' \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}" 2>/dev/null \
    | python3 -c 'import sys,json;print(json.load(sys.stdin).get("token",""))' 2>/dev/null)
  if [ -n "$TOKEN" ] && [ "$TOKEN" != "" ]; then
    curl -s -X POST http://localhost:8000/api/v1/config/deploy \
      -H "Authorization: Bearer $TOKEN" >/dev/null 2>&1
    echo "  ✓ Asterisk config deployed"
  fi
fi

# ── Done ──
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Astradial is ready!                                     ║"
echo "║                                                          ║"
echo "║  Dashboard:  http://localhost:3001                        ║"
echo "║  Login:      ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
echo "║                                                          ║"

if [ "$MODE" = "full" ]; then
echo "║  Mode: Full setup (Linux/VPS)                            ║"
echo "║  SIP:  ${SIP_HOST}:${SIP_PORT}"
echo "║                                                          ║"
echo "║  Create extensions in the dashboard, then register       ║"
echo "║  Zoiper with the SIP credentials shown in Users page.   ║"
else
echo "║  Mode: Astradial Cloud (Mac/Windows)                     ║"
echo "║  SIP:  ${SIP_HOST}:${SIP_PORT}"
echo "║                                                          ║"
echo "║  For SIP credentials, email cats@astradial.com           ║"
echo "║  You'll receive a phone number + extension login.        ║"
echo "║  Register Zoiper with those credentials to make calls.  ║"
fi

echo "║                                                          ║"
echo "║  Next steps:                                             ║"
echo "║  1. Open http://localhost:3001                            ║"
echo "║  2. Admin tab → login → create organisation              ║"
echo "║  3. Enter org → Users, CRM, Calls, Phone Numbers        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
