#!/bin/bash
set -e

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       Astradial — Quick Setup            ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "Docker is required. Install: https://docker.com"; exit 1; }

# Create .env if not exists
if [ ! -f .env ]; then
  cp .env.example .env
fi

# ── Admin credentials ──
echo "Set up your admin account:"
read -p "  Email [admin@example.com]: " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
read -p "  Password [admin]: " ADMIN_PASSWORD
ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
read -p "  Name [Admin]: " ADMIN_NAME
ADMIN_NAME=${ADMIN_NAME:-Admin}

# ── SIP mode ──
echo ""
echo "How do you want to run Astradial?"
echo ""
echo "  1) UI only — develop without phone calls (Mac/Windows)"
echo "  2) Full setup — includes Asterisk PBX for calls (Linux)"
echo ""
echo "  To connect a SIP trunk later, use the Trunks page in the dashboard."
echo "  For a free developer trunk, email cats@astradial.com"
echo ""
read -p "  Choice [1]: " SIP_MODE
SIP_MODE=${SIP_MODE:-1}

# ── Detect LAN IP ──
OS=$(uname -s)
if [ "$OS" = "Darwin" ]; then
  LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | grep -v "169.254" | head -1 | awk '{print $2}')
else
  LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 2>/dev/null | awk '{print $7;exit}')
fi
LAN_IP=${LAN_IP:-localhost}

# ── Write .env ──
cat > .env << EOF
# Generated by setup.sh
ASTRADIAL_MODE=selfhosted

# Database
DB_NAME=astradial
DB_USER=astradial
DB_PASSWORD=changeme
DB_ROOT_PASSWORD=changeme

# Security
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "change-this-to-a-random-string")
INTERNAL_API_KEY=$(openssl rand -hex 16 2>/dev/null || echo "change-this-to-a-random-string")

# Admin account
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}
ADMIN_USERNAME=admin
ADMIN_API_PASSWORD=${ADMIN_PASSWORD}

# Asterisk
ASTERISK_AMI_SECRET=astradial
SIP_HOST=${LAN_IP}
EOF

echo ""

# ── Build ──
echo "[1/5] Building Docker images... (first run takes 3-5 minutes)"
docker compose build 2>&1 | while IFS= read -r line; do
  if echo "$line" | grep -q " Built"; then
    service=$(echo "$line" | sed 's/ Built//')
    echo "  ✓ ${service} built"
  fi
done
echo "  ✓ All images built"

# ── Start database ──
echo "[2/5] Starting database..."
docker compose up -d mariadb redis 2>&1 >/dev/null
for i in $(seq 1 30); do
  if docker compose exec mariadb mariadb -u astradial -pchangeme -e "SELECT 1" >/dev/null 2>&1; then
    break
  fi
  printf "\r  ⏳ Waiting for database... (%s/30)" "$i"
  sleep 2
done
echo ""
echo "  ✓ Database ready"

# ── Start Asterisk (only for full setup) ──
if [ "$SIP_MODE" = "2" ]; then
  echo "[3/5] Starting Asterisk PBX..."
  docker compose up -d asterisk 2>&1 >/dev/null
  sleep 3
  echo "  ✓ Asterisk started"
else
  echo "[3/5] Skipping Asterisk (UI-only mode)"
fi

# ── Start API + Editor ──
echo "[4/5] Starting API and Dashboard..."
docker compose up -d api editor workflow-engine 2>&1 >/dev/null

for i in $(seq 1 30); do
  if curl -s http://localhost:8000/health >/dev/null 2>&1; then
    echo "  ✓ API is ready"
    break
  fi
  printf "\r  ⏳ Starting API... (%s/30)" "$i"
  sleep 2
done
echo ""

echo "[5/5] Finishing setup..."
for i in $(seq 1 15); do
  if curl -s http://localhost:3001 >/dev/null 2>&1; then
    echo "  ✓ Dashboard is ready"
    break
  fi
  sleep 2
done

# Deploy config if Asterisk is running
if [ "$SIP_MODE" = "2" ]; then
  TOKEN=$(curl -s -X POST http://localhost:8000/api/v1/auth/user-login \
    -H 'Content-Type: application/json' \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}" 2>/dev/null \
    | python3 -c 'import sys,json;print(json.load(sys.stdin).get("token",""))' 2>/dev/null)

  if [ -n "$TOKEN" ] && [ "$TOKEN" != "" ]; then
    curl -s -X POST http://localhost:8000/api/v1/config/deploy \
      -H "Authorization: Bearer $TOKEN" >/dev/null 2>&1
    echo "  ✓ Asterisk config deployed"
  fi
fi

# ── Done ──
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Astradial is ready!                                     ║"
echo "║                                                          ║"
echo "║  Dashboard:  http://localhost:3001                        ║"
echo "║  Login:      ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
echo "║                                                          ║"
if [ "$SIP_MODE" = "2" ]; then
echo "║  SIP Server: ${LAN_IP}:5060"
echo "║                                                          ║"
echo "║  To connect a SIP trunk:                                 ║"
echo "║  Dashboard → Trunks → Add Trunk → enter provider creds  ║"
else
echo "║  Mode: UI development (no Asterisk)                      ║"
echo "║                                                          ║"
echo "║  To enable calls, re-run: ./setup.sh and choose option 2 ║"
echo "║  Or connect a SIP trunk from: Dashboard → Trunks         ║"
fi
echo "║                                                          ║"
echo "║  For a free developer SIP trunk:                         ║"
echo "║  Email cats@astradial.com                                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
