#!/bin/bash
set -e

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       Astradial — Quick Setup            ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "Docker is required. Install: https://docker.com"; exit 1; }

# Create .env if not exists
if [ ! -f .env ]; then
  cp .env.example .env
fi

# ── Admin credentials ──
echo "Set up your admin account:"
read -p "  Email [admin@example.com]: " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
read -p "  Password [admin]: " ADMIN_PASSWORD
ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
read -p "  Name [Admin]: " ADMIN_NAME
ADMIN_NAME=${ADMIN_NAME:-Admin}

# ── SIP mode ──
echo ""
echo "How do you want to handle calls?"
echo ""
echo "  1) No SIP — UI development only (Mac/Windows)"
echo "  2) Full setup with SIP — extension-to-extension calls (Linux)"
echo "  3) Connect your own SIP trunk (Twilio, Telnyx, etc.)"
echo ""
echo "  Want a free Indian DID for testing?"
echo "  Email dev@astradial.com — we'll send you trunk credentials."
echo "  Then use option 3 to connect."
echo ""
read -p "  Choice [1]: " SIP_MODE
SIP_MODE=${SIP_MODE:-1}

SIP_TRUNK_HOST=""
SIP_TRUNK_USER=""
SIP_TRUNK_PASS=""
SIP_DID=""

if [ "$SIP_MODE" = "3" ]; then
  echo ""
  echo "Enter your SIP trunk credentials:"
  read -p "  SIP Server (e.g. sip.telnyx.com): " SIP_TRUNK_HOST
  read -p "  Username: " SIP_TRUNK_USER
  read -p "  Password: " SIP_TRUNK_PASS
  read -p "  DID Number (e.g. +14155551234): " SIP_DID
fi

# ── Detect LAN IP ──
OS=$(uname -s)
if [ "$OS" = "Darwin" ]; then
  LAN_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | grep -v "169.254" | head -1 | awk '{print $2}')
else
  LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 2>/dev/null | awk '{print $7;exit}')
fi
LAN_IP=${LAN_IP:-localhost}

# ── Write .env ──
cat > .env << EOF
# Generated by setup.sh
ASTRADIAL_MODE=selfhosted

# Database
DB_NAME=astradial
DB_USER=astradial
DB_PASSWORD=changeme
DB_ROOT_PASSWORD=changeme

# Security
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "change-this-to-a-random-string")
INTERNAL_API_KEY=$(openssl rand -hex 16 2>/dev/null || echo "change-this-to-a-random-string")

# Admin account
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}
ADMIN_USERNAME=admin
ADMIN_API_PASSWORD=${ADMIN_PASSWORD}

# Asterisk
ASTERISK_AMI_SECRET=astradial
SIP_HOST=${LAN_IP}

# SIP Trunk (option 3)
ASTRADIAL_TRUNK_HOST=${SIP_TRUNK_HOST}
ASTRADIAL_TRUNK_USER=${SIP_TRUNK_USER}
ASTRADIAL_TRUNK_PASS=${SIP_TRUNK_PASS}
EOF

echo ""

# ── Build ──
echo "[1/5] Building Docker images... (first run takes 3-5 minutes)"
docker compose build 2>&1 | while IFS= read -r line; do
  if echo "$line" | grep -q " Built"; then
    service=$(echo "$line" | sed 's/ Built//')
    echo "  ✓ ${service} built"
  fi
done
echo "  ✓ All images built"

# ── Start based on mode ──
if [ "$SIP_MODE" = "1" ]; then
  # No SIP — skip Asterisk
  echo "[2/5] Starting database..."
  docker compose up -d mariadb redis 2>&1 >/dev/null
  for i in $(seq 1 30); do
    if docker compose exec mariadb mariadb -u astradial -pchangeme -e "SELECT 1" >/dev/null 2>&1; then
      break
    fi
    printf "\r  ⏳ Waiting for database... (%s/30)" "$i"
    sleep 2
  done
  echo ""
  echo "  ✓ Database ready"

  echo "[3/5] Skipping Asterisk (No SIP mode)"
  echo "  ✓ Skipped"

  echo "[4/5] Starting API and Dashboard..."
  docker compose up -d api editor workflow-engine 2>&1 >/dev/null
else
  # Full setup or own trunk
  echo "[2/5] Starting database..."
  docker compose up -d mariadb redis 2>&1 >/dev/null
  for i in $(seq 1 30); do
    if docker compose exec mariadb mariadb -u astradial -pchangeme -e "SELECT 1" >/dev/null 2>&1; then
      break
    fi
    printf "\r  ⏳ Waiting for database... (%s/30)" "$i"
    sleep 2
  done
  echo ""
  echo "  ✓ Database ready"

  echo "[3/5] Starting Asterisk PBX..."
  docker compose up -d asterisk 2>&1 >/dev/null
  sleep 3
  echo "  ✓ Asterisk started"

  echo "[4/5] Starting API and Dashboard..."
  docker compose up -d api editor workflow-engine 2>&1 >/dev/null
fi

# Wait for API
for i in $(seq 1 30); do
  if curl -s http://localhost:8000/health >/dev/null 2>&1; then
    echo "  ✓ API is ready"
    break
  fi
  printf "\r  ⏳ Starting API... (%s/30)" "$i"
  sleep 2
done
echo ""

echo "[5/5] Finishing setup..."

# Wait for editor
for i in $(seq 1 15); do
  if curl -s http://localhost:3001 >/dev/null 2>&1; then
    echo "  ✓ Dashboard is ready"
    break
  fi
  sleep 2
done

# Deploy Asterisk config (if SIP enabled)
if [ "$SIP_MODE" != "1" ]; then
  TOKEN=$(curl -s -X POST http://localhost:8000/api/v1/auth/user-login \
    -H 'Content-Type: application/json' \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}" 2>/dev/null \
    | python3 -c 'import sys,json;print(json.load(sys.stdin).get("token",""))' 2>/dev/null)

  if [ -n "$TOKEN" ] && [ "$TOKEN" != "" ]; then
    curl -s -X POST http://localhost:8000/api/v1/config/deploy \
      -H "Authorization: Bearer $TOKEN" >/dev/null 2>&1
    echo "  ✓ Asterisk config deployed"

    # If option 3 with DID, create trunk + DID via API
    if [ "$SIP_MODE" = "3" ] && [ -n "$SIP_TRUNK_HOST" ]; then
      # Create trunk
      TRUNK_RESULT=$(curl -s -X POST http://localhost:8000/api/v1/trunks \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/json" \
        -d "{\"name\":\"My SIP Trunk\",\"host\":\"${SIP_TRUNK_HOST}\",\"port\":5060,\"transport\":\"udp\",\"trunk_type\":\"outbound\",\"username\":\"${SIP_TRUNK_USER}\",\"password\":\"${SIP_TRUNK_PASS}\"}" 2>/dev/null)
      TRUNK_ID=$(echo "$TRUNK_RESULT" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("id",""))' 2>/dev/null)

      if [ -n "$TRUNK_ID" ] && [ "$TRUNK_ID" != "" ]; then
        echo "  ✓ SIP trunk created"

        # Create DID if provided
        if [ -n "$SIP_DID" ]; then
          curl -s -X POST http://localhost:8000/api/v1/dids \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"number\":\"${SIP_DID}\",\"trunk_id\":\"${TRUNK_ID}\",\"routing_type\":\"extension\",\"routing_destination\":\"1001\"}" >/dev/null 2>&1
          echo "  ✓ DID ${SIP_DID} → extension 1001"
        fi

        # Redeploy config with trunk
        curl -s -X POST http://localhost:8000/api/v1/config/deploy \
          -H "Authorization: Bearer $TOKEN" >/dev/null 2>&1
        echo "  ✓ Config redeployed with trunk"
      fi
    fi
  fi
fi

# ── Done ──
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Astradial is ready!                                     ║"
echo "║                                                          ║"
echo "║  Dashboard:  http://localhost:3001                        ║"
echo "║  Login:      ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
echo "║                                                          ║"

if [ "$SIP_MODE" = "1" ]; then
echo "║  Mode: UI development (no SIP)                           ║"
echo "║  To test calls, use a Linux server or connect a trunk.   ║"
elif [ "$SIP_MODE" = "2" ]; then
echo "║  Mode: Full setup with SIP                               ║"
echo "║  SIP Server: ${LAN_IP}:5060"
echo "║  Register Zoiper → Users page → click extension → creds ║"
elif [ "$SIP_MODE" = "3" ]; then
echo "║  Mode: Own SIP trunk (${SIP_TRUNK_HOST})"
echo "║  SIP Server: ${LAN_IP}:5060"
if [ -n "$SIP_DID" ]; then
echo "║  DID: ${SIP_DID} → rings extension 1001"
fi
fi

echo "║                                                          ║"
echo "║  Next steps:                                             ║"
echo "║  1. Open http://localhost:3001                            ║"
echo "║  2. Sign in → Organisation tab                           ║"
echo "║  3. Explore: Users, CRM, Calls, Phone Numbers            ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
