[general]
static=yes
writeprotect=no

[internal]
; Dial extensions
exten => 1001,1,NoOp(Dialing Alice)
 same => n,Dial(PJSIP/org_mmi4ipkn__1001,30,rtT)
 same => n,Hangup()

exten => 1002,1,NoOp(Dialing Bob)
 same => n,Dial(PJSIP/org_mmi4ipkn__1002,30,rtT)
 same => n,Hangup()

; Echo test
exten => 9999,1,Answer()
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()
