; ── Transports ──

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089

; ── Alice (1001) ──

[org_mmi4ipkn__1001]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
allow=opus
auth=org_mmi4ipkn__1001_auth
aors=org_mmi4ipkn__1001_aor
callerid="Alice" <1001>
webrtc=yes
transport=transport-udp
identify_by=username,auth_username

[org_mmi4ipkn__1001_auth]
type=auth
auth_type=userpass
username=org_mmi4ipkn__1001
password=55d1d3c5-f22

[org_mmi4ipkn__1001_aor]
type=aor
max_contacts=5
remove_existing=yes

; ── Bob (1002) ──

[org_mmi4ipkn__1002]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
allow=opus
auth=org_mmi4ipkn__1002_auth
aors=org_mmi4ipkn__1002_aor
callerid="Bob" <1002>
webrtc=yes
transport=transport-udp
identify_by=username,auth_username

[org_mmi4ipkn__1002_auth]
type=auth
auth_type=userpass
username=org_mmi4ipkn__1002
password=72677896-02e

[org_mmi4ipkn__1002_aor]
type=aor
max_contacts=5
remove_existing=yes
