const fs = require('fs').promises;

/**
 * Music on Hold Service
 * Generates musiconhold.conf for Asterisk
 */
class MusicOnHoldService {
  constructor() {
    this.configPath = process.env.ASTERISK_MOH_CONFIG_PATH || '/etc/asterisk/musiconhold.conf';
    this.mohDirectory = process.env.ASTERISK_MOH_DIRECTORY || '/var/lib/asterisk/moh';
  }

  /**
   * Generate complete Music on Hold configuration
   */
  async generateConfiguration() {
    try {
      console.log('🎵 Generating Music on Hold configuration...');

      let config = `; Music on Hold Configuration\n`;
      config += `; Auto-generated by PBX API\n`;
      config += `; Generated at: ${new Date().toISOString()}\n\n`;

      // Default MOH class
      config += `[default]\n`;
      config += `mode=files\n`;
      config += `directory=${this.mohDirectory}/default\n`;
      config += `sort=random\n`;
      config += `\n`;

      // Alternative MOH classes
      config += `[classical]\n`;
      config += `mode=files\n`;
      config += `directory=${this.mohDirectory}/classical\n`;
      config += `sort=random\n`;
      config += `\n`;

      config += `[modern]\n`;
      config += `mode=files\n`;
      config += `directory=${this.mohDirectory}/modern\n`;
      config += `sort=random\n`;
      config += `\n`;

      config += `[jazz]\n`;
      config += `mode=files\n`;
      config += `directory=${this.mohDirectory}/jazz\n`;
      config += `sort=random\n`;
      config += `\n`;

      // Custom hold music (silence or custom audio)
      config += `[silence]\n`;
      config += `mode=files\n`;
      config += `directory=${this.mohDirectory}/silence\n`;
      config += `\n`;

      // Scan for org-specific MOH directories (org_*_*)
      try {
        const entries = await fs.readdir(this.mohDirectory);
        for (const entry of entries) {
          if (entry.startsWith('org_')) {
            const dirPath = `${this.mohDirectory}/${entry}`;
            const stat = await fs.stat(dirPath);
            if (stat.isDirectory()) {
              config += `[${entry}]\n`;
              config += `mode=files\n`;
              config += `directory=${dirPath}\n`;
              config += `sort=random\n`;
              config += `\n`;
            }
          }
        }
      } catch (scanErr) {
        console.warn('⚠️  Could not scan for org MOH directories:', scanErr.message);
      }

      console.log('✅ Music on Hold configuration generated');
      return config;

    } catch (error) {
      console.error('❌ Error generating MOH configuration:', error);
      throw error;
    }
  }

  /**
   * Write configuration to file
   */
  async writeConfigurationFile(filePath = null) {
    try {
      const targetPath = filePath || this.configPath;
      const config = await this.generateConfiguration();

      // Create backup
      try {
        await this.createBackup(targetPath);
      } catch (backupError) {
        console.warn('⚠️  Could not create backup:', backupError.message);
      }

      // Write new configuration
      await fs.writeFile(targetPath, config, 'utf8');
      console.log(`✅ Music on Hold configuration written to: ${targetPath}`);

      return targetPath;

    } catch (error) {
      console.error('❌ Error writing MOH configuration file:', error);
      throw error;
    }
  }

  /**
   * Create backup of existing configuration
   */
  async createBackup(filePath) {
    try {
      const stats = await fs.stat(filePath);
      if (stats.isFile()) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const backupPath = `${filePath}.backup.${timestamp}`;
        await fs.copyFile(filePath, backupPath);
        console.log(`📋 Created backup: ${backupPath}`);
      }
    } catch (error) {
      if (error.code !== 'ENOENT') {
        throw error;
      }
    }
  }

  /**
   * Reload Music on Hold in Asterisk
   */
  async reloadMusicOnHold() {
    try {
      console.log('🔄 Reloading Asterisk Music on Hold...');

      const { exec } = require('child_process');
      const { promisify } = require('util');
      const execAsync = promisify(exec);

      const { stdout, stderr } = await execAsync('asterisk -rx "moh reload"');

      if (stderr) {
        console.warn('⚠️  Reload warnings:', stderr);
      }

      console.log('✅ Music on Hold reloaded successfully');
      return { success: true, output: stdout };

    } catch (error) {
      console.error('❌ Error reloading Music on Hold:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Deploy complete MOH configuration
   */
  async deploy() {
    try {
      console.log('🚀 Deploying Music on Hold configuration...');

      // Write configuration file
      await this.writeConfigurationFile();

      // Reload Asterisk MOH
      const reloadResult = await this.reloadMusicOnHold();

      if (!reloadResult.success) {
        throw new Error(`Failed to reload Music on Hold: ${reloadResult.error}`);
      }

      console.log('✅ Music on Hold configuration deployed successfully');
      return { success: true, message: 'MOH configuration deployed and Asterisk reloaded' };

    } catch (error) {
      console.error('❌ Error deploying MOH configuration:', error);
      throw error;
    }
  }

  /**
   * Get available MOH classes
   */
  async getAvailableClasses() {
    try {
      const { exec } = require('child_process');
      const { promisify } = require('util');
      const execAsync = promisify(exec);

      const { stdout } = await execAsync('asterisk -rx "moh show classes"');

      // Parse output to extract MOH classes
      const classes = [];
      const lines = stdout.split('\n');

      for (const line of lines) {
        // Look for lines that start with class name
        const match = line.match(/^(\w+)\s+:/);
        if (match) {
          classes.push(match[1]);
        }
      }

      return {
        classes,
        raw_output: stdout
      };

    } catch (error) {
      console.error('❌ Error getting MOH classes:', error);
      return { classes: [], error: error.message };
    }
  }

  /**
   * Verify MOH directories exist
   */
  async verifyDirectories() {
    try {
      const directories = [
        `${this.mohDirectory}/default`,
        `${this.mohDirectory}/classical`,
        `${this.mohDirectory}/modern`,
        `${this.mohDirectory}/jazz`,
        `${this.mohDirectory}/silence`
      ];

      const results = [];

      for (const dir of directories) {
        try {
          await fs.access(dir);
          results.push({ directory: dir, exists: true });
        } catch (error) {
          results.push({ directory: dir, exists: false, error: 'Directory not found' });
        }
      }

      return results;

    } catch (error) {
      console.error('❌ Error verifying MOH directories:', error);
      throw error;
    }
  }

  /**
   * Ensure an org-specific MOH class exists in musiconhold.conf
   */
  async ensureOrgClass(contextPrefix, className) {
    try {
      const mohClass = `${contextPrefix}_${className}`;
      const configContent = await fs.readFile(this.configPath, 'utf8').catch(() => '');

      if (configContent.includes(`[${mohClass}]`)) {
        return; // Already exists
      }

      // Append org class to config
      const classConfig = `\n[${mohClass}]\nmode=files\ndirectory=${this.mohDirectory}/${mohClass}\nsort=random\n`;
      await fs.appendFile(this.configPath, classConfig);
      console.log(`✅ Added MOH class: ${mohClass}`);
    } catch (error) {
      console.error(`❌ Error adding MOH class:`, error);
      throw error;
    }
  }

  /**
   * Create MOH directories if they don't exist
   */
  async createDirectories() {
    try {
      console.log('📁 Creating Music on Hold directories...');

      const directories = [
        `${this.mohDirectory}/default`,
        `${this.mohDirectory}/classical`,
        `${this.mohDirectory}/modern`,
        `${this.mohDirectory}/jazz`,
        `${this.mohDirectory}/silence`
      ];

      for (const dir of directories) {
        try {
          await fs.mkdir(dir, { recursive: true });
          console.log(`✅ Created: ${dir}`);
        } catch (error) {
          if (error.code !== 'EEXIST') {
            console.error(`❌ Failed to create ${dir}:`, error.message);
          }
        }
      }

      console.log('✅ MOH directories created');
      return { success: true };

    } catch (error) {
      console.error('❌ Error creating MOH directories:', error);
      throw error;
    }
  }
}

module.exports = MusicOnHoldService;
