/**
 * WireGuard config generator for customer tunnels (wg1).
 *
 * Generates the contents of /etc/wireguard/wg1.conf from the customer_tunnels
 * DB table. This service is RENDER-ONLY — it returns the config as a string.
 * The actual file write + `wg syncconf` reload lives in wireguardApplier
 * (next PR) so that:
 *   - Tests can verify the rendered output without filesystem side-effects
 *   - The apply step can be retried/audited independently of generation
 *   - Multiple consumers can use the same rendered output (e.g., the API's
 *     `GET /tunnels/:id/customer-config` endpoint reuses peer-block rendering)
 *
 *
 * ──────────────────────────────────────────────────────────────────────────
 *  Output shape (wg1.conf — server side)
 * ──────────────────────────────────────────────────────────────────────────
 *
 *  # AUTO-GENERATED by AstraPBX wireguardGenerator. DO NOT EDIT BY HAND.
 *  # Source of truth: customer_tunnels table in pbx_api_db.
 *  # Generated: 2026-05-12T13:30:00.000Z
 *
 *  [Interface]
 *  Address = 10.20.0.1/16
 *  ListenPort = 51821
 *  PrivateKey = <server-private-key>
 *  PostUp = /usr/local/sbin/customer-tunnels-iptables.sh up
 *  PostDown = /usr/local/sbin/customer-tunnels-iptables.sh down
 *
 *  # org=<uuid> name=astradial-v7 created=2026-05-12T13:25:00.000Z
 *  [Peer]
 *  PublicKey = <customer-pubkey>
 *  PresharedKey = <psk>
 *  AllowedIPs = 10.20.7.2/32
 *  PersistentKeepalive = 25
 *
 *  ... (one [Peer] block per active customer_tunnel row)
 *
 *
 * ──────────────────────────────────────────────────────────────────────────
 *  Security notes
 * ──────────────────────────────────────────────────────────────────────────
 *
 *  - Server private key is read from disk (default: /etc/wireguard/wg1.private).
 *    It must NEVER be returned via the API, logged, or stored in DB.
 *    Caller must keep the rendered output server-side only.
 *  - Pre-shared keys for each peer are pulled from DB via the `withSecrets`
 *    scope on CustomerTunnel — they remain server-side, never returned to
 *    clients (the `customer-config` endpoint emits a peer block with the
 *    PSK; that's expected because the customer needs the PSK to configure
 *    their router).
 *  - Header comment in the output marks the file as auto-generated so
 *    operators don't hand-edit and lose changes on the next regen.
 *
 *
 * ──────────────────────────────────────────────────────────────────────────
 *  Determinism
 * ──────────────────────────────────────────────────────────────────────────
 *
 *  Peers are rendered in `created_at ASC` order. Calling
 *  `generateWg1Config()` twice in succession with the same DB state produces
 *  byte-identical output (except the "Generated:" timestamp comment, which is
 *  the only non-deterministic field).
 *
 *  See: docs/features/customer-tunnels.md for the broader design.
 */

'use strict';

const fs = require('node:fs/promises');
const path = require('node:path');

// Default file locations on the cloud VPS. Override via options for tests.
const DEFAULT_PRIVATE_KEY_PATH = '/etc/wireguard/wg1.private';
const DEFAULT_PUBLIC_KEY_PATH = '/etc/wireguard/wg1.public';

// Interface defaults — match the design doc + bootstrap script.
const DEFAULT_INTERFACE_ADDRESS = '10.20.0.1/16';
const DEFAULT_LISTEN_PORT = 51821;
const DEFAULT_POST_UP = '/usr/local/sbin/customer-tunnels-iptables.sh up';
const DEFAULT_POST_DOWN = '/usr/local/sbin/customer-tunnels-iptables.sh down';

// WireGuard key format: base64-encoded 32 bytes = 44 chars (43 + '=').
const WG_KEY_REGEX = /^[A-Za-z0-9+/]{43}=$/;

// IPv4 host address validator (no CIDR suffix). Loose but sufficient — we
// only use this to verify routed-IPs are well-formed before rendering.
// Allows 0-255 per octet via the simpler regex + a numeric range check below.
const IPV4_REGEX = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;

/**
 * Validate an IPv4 host address (no CIDR). Throws on failure.
 * @param {string} ip
 * @param {string} [label='IPv4 address']
 */
function assertValidIpv4(ip, label = 'IPv4 address') {
  if (typeof ip !== 'string') {
    throw new Error(`Invalid ${label}: expected string, got ${typeof ip}`);
  }
  const m = IPV4_REGEX.exec(ip);
  if (!m) {
    throw new Error(`Invalid ${label}: "${ip}" is not a valid IPv4 address`);
  }
  for (let i = 1; i <= 4; i++) {
    const octet = Number(m[i]);
    if (octet < 0 || octet > 255) {
      throw new Error(`Invalid ${label}: "${ip}" has octet out of range (0-255)`);
    }
  }
}

/**
 * Validate a WireGuard key string. Throws if it doesn't match the expected
 * 44-character base64 shape. Used to fail fast on corrupted DB rows or
 * filesystem reads.
 *
 * @param {string} key
 * @param {string} [label='key'] - used in the thrown error message
 */
function assertValidWgKey(key, label = 'key') {
  if (typeof key !== 'string' || !WG_KEY_REGEX.test(key)) {
    throw new Error(`Invalid WireGuard ${label}: expected 44-char base64, got ${typeof key === 'string' ? `"${key.slice(0, 8)}..." (length ${key.length})` : typeof key}`);
  }
}

/**
 * Render the [Interface] block for wg1.conf.
 *
 * @param {object} opts
 * @param {string} opts.private_key - 44-char base64 WG private key
 * @param {string} [opts.address] - interface IP/mask (default 10.20.0.1/16)
 * @param {number} [opts.listen_port] - UDP listen port (default 51821)
 * @param {string} [opts.post_up] - PostUp shell command
 * @param {string} [opts.post_down] - PostDown shell command
 * @returns {string}
 */
function renderInterfaceBlock({
  private_key,
  address = DEFAULT_INTERFACE_ADDRESS,
  listen_port = DEFAULT_LISTEN_PORT,
  post_up = DEFAULT_POST_UP,
  post_down = DEFAULT_POST_DOWN
} = {}) {
  assertValidWgKey(private_key, 'server private key');
  return [
    '[Interface]',
    `Address = ${address}`,
    `ListenPort = ${listen_port}`,
    `PrivateKey = ${private_key}`,
    `PostUp = ${post_up}`,
    `PostDown = ${post_down}`,
    ''
  ].join('\n');
}

/**
 * Render a single server-side [Peer] block for wg1.conf.
 *
 * AllowedIPs:
 *   - Always: customer's tunnel-side /32 (e.g. 10.20.0.2/32) — required so the
 *     server can route return traffic and WireGuard cryptokey-routing accepts
 *     packets sourced from that IP.
 *   - Optional: customer's LAN CIDR (e.g. 192.168.0.0/24) when the tunnel row
 *     has `customer_lan_cidr` set. Required so packets sourced from a device
 *     on the customer's LAN (e.g. a phone at 192.168.0.76) pass the inbound
 *     cryptokey check on the server side — without it, WireGuard kernel
 *     module silently drops the packet (rx_errors increments).
 *
 * Caller is expected to have validated customer_lan_cidr semantically
 * before passing it in (see assertValidCustomerLanCidr in
 * customer-tunnels-helpers). This function trusts the input.
 *
 * @param {object} tunnel - tunnel data (DB row or plain object)
 * @param {string} tunnel.org_id
 * @param {string} tunnel.name
 * @param {string} tunnel.customer_pubkey
 * @param {string} tunnel.preshared_key
 * @param {string} tunnel.customer_tunnel_ip
 * @param {string} [tunnel.customer_lan_cidr]
 * @param {number} [tunnel.persistent_keepalive=25]
 * @param {Date|string} [tunnel.created_at]
 * @returns {string}
 */
function renderPeerBlock(tunnel) {
  if (!tunnel) throw new Error('renderPeerBlock: tunnel is required');
  assertValidWgKey(tunnel.customer_pubkey, 'customer pubkey');
  assertValidWgKey(tunnel.preshared_key, 'pre-shared key');
  const created = tunnel.created_at instanceof Date
    ? tunnel.created_at.toISOString()
    : (typeof tunnel.created_at === 'string' ? tunnel.created_at : '');
  const keepalive = tunnel.persistent_keepalive ?? 25;

  const allowedIps = [`${tunnel.customer_tunnel_ip}/32`];
  if (tunnel.customer_lan_cidr && typeof tunnel.customer_lan_cidr === 'string') {
    allowedIps.push(tunnel.customer_lan_cidr);
  }

  return [
    `# org=${tunnel.org_id} name=${tunnel.name} created=${created}`,
    '[Peer]',
    `PublicKey = ${tunnel.customer_pubkey}`,
    `PresharedKey = ${tunnel.preshared_key}`,
    `AllowedIPs = ${allowedIps.join(', ')}`,
    `PersistentKeepalive = ${keepalive}`,
    ''
  ].join('\n');
}

/**
 * Render the customer-side [Peer] block — what the API returns for an
 * operator to paste into the customer's router (e.g., GDMS WireGuard config).
 *
 * The customer's [Peer] block describes US (the cloud), not them. So it
 * needs the cloud's public key and endpoint, not the customer's.
 *
 * AllowedIPs semantics:
 *   - Always includes the cloud-side tunnel IP (e.g., 10.20.7.1/32) so the
 *     customer can route to us at our tunnel address.
 *   - Optionally includes additional cloud-side IPs via `cloud_routed_ips`.
 *     The common case is to include the cloud's public IP (203.0.113.1)
 *     so that traffic to sip.example.com (which resolves to the public
 *     IP) routes through the tunnel rather than the customer's default ISP
 *     route. Without this, the tunnel exists but SIP traffic bypasses it.
 *   - Resolves duplicates and keeps a stable order (tunnel IP first, routed
 *     IPs after in input order).
 *
 * WireGuard handshake packets to the Endpoint are never routed through the
 * tunnel even if the endpoint IP is in AllowedIPs (special-cased by WG).
 * So putting 203.0.113.1 in AllowedIPs is safe and correct.
 *
 * @param {object} opts
 * @param {object} opts.tunnel - tunnel row (must include preshared_key)
 * @param {string} opts.cloud_public_key
 * @param {string} opts.cloud_endpoint - e.g. "203.0.113.1:51821" or "host:port"
 * @param {string[]} [opts.cloud_routed_ips=[]] - additional IPv4 host IPs
 *   (no CIDR) to add to AllowedIPs; each becomes "<ip>/32"
 * @returns {string}
 */
function renderCustomerSidePeer({ tunnel, cloud_public_key, cloud_endpoint, cloud_routed_ips = [] }) {
  if (!tunnel) throw new Error('renderCustomerSidePeer: tunnel is required');
  assertValidWgKey(cloud_public_key, 'cloud public key');
  assertValidWgKey(tunnel.preshared_key, 'pre-shared key');
  if (!cloud_endpoint || typeof cloud_endpoint !== 'string') {
    throw new Error('renderCustomerSidePeer: cloud_endpoint is required (e.g. "203.0.113.1:51821")');
  }
  if (!Array.isArray(cloud_routed_ips)) {
    throw new Error('renderCustomerSidePeer: cloud_routed_ips must be an array of IPv4 strings');
  }
  // Validate every routed IP before rendering so we fail loud on bad input.
  for (const ip of cloud_routed_ips) {
    assertValidIpv4(ip, 'cloud_routed_ips entry');
  }
  const keepalive = tunnel.persistent_keepalive ?? 25;

  // AllowedIPs: tunnel IP first, then each routed IP (deduplicated, order preserved).
  const allowedSet = new Set();
  allowedSet.add(`${tunnel.cloud_tunnel_ip}/32`);
  for (const ip of cloud_routed_ips) {
    allowedSet.add(`${ip}/32`);
  }
  const allowedIPs = Array.from(allowedSet).join(', ');

  return [
    '# Astradial cloud — paste this [Peer] block in your router WireGuard config',
    '[Peer]',
    `PublicKey = ${cloud_public_key}`,
    `PresharedKey = ${tunnel.preshared_key}`,
    `AllowedIPs = ${allowedIPs}`,
    `Endpoint = ${cloud_endpoint}`,
    `PersistentKeepalive = ${keepalive}`,
    ''
  ].join('\n');
}

/**
 * Render the full wg1.conf content given the interface settings + array
 * of peer data objects.
 *
 * Pure function — no DB, no filesystem. Used as the rendering primitive
 * for both `generateWg1Config()` (which adds the DB query) and tests.
 *
 * @param {object} opts
 * @param {string} opts.private_key
 * @param {object[]} opts.peers - already sorted; renderer doesn't sort
 * @param {Date} [opts.generated_at] - for deterministic timestamp in tests
 * @param {string} [opts.address]
 * @param {number} [opts.listen_port]
 * @param {string} [opts.post_up]
 * @param {string} [opts.post_down]
 * @returns {string}
 */
function renderWg1Config({
  private_key,
  peers = [],
  generated_at = new Date(),
  address,
  listen_port,
  post_up,
  post_down
} = {}) {
  const header = [
    '# AUTO-GENERATED by AstraPBX wireguardGenerator. DO NOT EDIT BY HAND.',
    '# Source of truth: customer_tunnels table in pbx_api_db.',
    `# Generated: ${generated_at.toISOString()}`,
    ''
  ].join('\n');

  const interfaceBlock = renderInterfaceBlock({ private_key, address, listen_port, post_up, post_down });

  const peerBlocks = peers.map(renderPeerBlock).join('\n');

  return header + '\n' + interfaceBlock + (peers.length > 0 ? '\n' + peerBlocks : '');
}

/**
 * Read the server's WireGuard private key from disk.
 *
 * @param {string} [keyPath]
 * @returns {Promise<string>}
 */
async function loadServerPrivateKey(keyPath = DEFAULT_PRIVATE_KEY_PATH) {
  const raw = await fs.readFile(keyPath, 'utf8');
  const key = raw.trim();
  assertValidWgKey(key, `server private key at ${keyPath}`);
  return key;
}

/**
 * Read the server's WireGuard public key from disk.
 *
 * @param {string} [keyPath]
 * @returns {Promise<string>}
 */
async function loadServerPublicKey(keyPath = DEFAULT_PUBLIC_KEY_PATH) {
  const raw = await fs.readFile(keyPath, 'utf8');
  const key = raw.trim();
  assertValidWgKey(key, `server public key at ${keyPath}`);
  return key;
}

/**
 * Query DB for active customer tunnels (sorted by created_at ASC).
 * Uses the `withSecrets` scope to include preshared_key.
 *
 * @param {object} opts
 * @param {object} opts.models
 * @returns {Promise<object[]>}
 */
async function getActiveTunnels({ models } = {}) {
  if (!models || !models.CustomerTunnel) {
    throw new Error('getActiveTunnels requires { models: { CustomerTunnel } }');
  }
  const { CustomerTunnel } = models;
  const tunnels = await CustomerTunnel.scope('withSecrets').findAll({
    where: { status: 'active' },
    order: [['created_at', 'ASC']]
  });
  return tunnels;
}

/**
 * Top-level: read server private key + query DB + render full wg1.conf.
 *
 * @param {object} opts
 * @param {object} opts.models
 * @param {string} [opts.privateKeyPath]
 * @param {string} [opts.address]
 * @param {number} [opts.listenPort]
 * @param {string} [opts.postUp]
 * @param {string} [opts.postDown]
 * @param {Date} [opts.generatedAt]
 * @returns {Promise<{config: string, peerCount: number, tunnels: object[]}>}
 *   - tunnels exposed so callers (notably wireguardApplier.syncCustomerLanRoutes)
 *     don't have to re-query the DB. Returned as plain rows; treat as
 *     read-only.
 */
async function generateWg1Config({
  models,
  privateKeyPath = DEFAULT_PRIVATE_KEY_PATH,
  address,
  listenPort,
  postUp,
  postDown,
  generatedAt
} = {}) {
  const privateKey = await loadServerPrivateKey(privateKeyPath);
  const tunnels = await getActiveTunnels({ models });
  const config = renderWg1Config({
    private_key: privateKey,
    peers: tunnels,
    address,
    listen_port: listenPort,
    post_up: postUp,
    post_down: postDown,
    generated_at: generatedAt
  });
  return { config, peerCount: tunnels.length, tunnels };
}

module.exports = {
  // Constants
  DEFAULT_PRIVATE_KEY_PATH,
  DEFAULT_PUBLIC_KEY_PATH,
  DEFAULT_INTERFACE_ADDRESS,
  DEFAULT_LISTEN_PORT,
  DEFAULT_POST_UP,
  DEFAULT_POST_DOWN,
  // Pure renderers (testable without DB or filesystem)
  renderInterfaceBlock,
  renderPeerBlock,
  renderCustomerSidePeer,
  renderWg1Config,
  assertValidWgKey,
  assertValidIpv4,
  // I/O helpers
  loadServerPrivateKey,
  loadServerPublicKey,
  getActiveTunnels,
  // Top-level
  generateWg1Config
};
