#!/bin/bash
# Entry script for the bundled api + asterisk image.
#
# Order matters:
#   1. Render runtime asterisk configs (NAT IP, AMI secret) from env.
#      These overwrite the seed configs that ship in the image.
#   2. Wait for the external mariadb container to be reachable.
#   3. Bootstrap-or-migrate the schema, run the admin seed.
#   4. Hand off to supervisord which runs asterisk + node side-by-side.
#
# Steps 1-3 happen ONCE before any long-running process starts, so a
# failed migration exits the container cleanly (docker-compose will
# restart per its policy, surfacing the error in logs).

set -e

echo "=== Astradial single-container starting ==="
echo "Mode: ${ASTRADIAL_MODE:-selfhosted}"

############################################################################
# 1. Asterisk runtime config
############################################################################

# Detect host IP for SIP NAT — same heuristic the old standalone asterisk
# entrypoint used. SIP_HOST env wins; fall back to host.docker.internal
# (Linux gets this via the extra_hosts entry in compose) or the default
# route gateway.
HOST_IP=${SIP_HOST:-$(getent ahostsv4 host.docker.internal 2>/dev/null | head -1 | awk '{print $1}' || ip route | grep default | awk '{print $3}')}
echo "Host IP for SIP NAT: ${HOST_IP}"

cat > /etc/asterisk/pjsip.conf <<PJSIP
; Auto-generated by entrypoint.sh at container start. The Astradial
; config deploy service appends per-org #include directives below.
[global]
type=global
max_forwards=70
user_agent=Astradial PBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=${HOST_IP}
external_signaling_address=${HOST_IP}
local_net=172.16.0.0/12

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_media_address=${HOST_IP}
external_signaling_address=${HOST_IP}
local_net=172.16.0.0/12
PJSIP

# RTP port range — must match the udp port range forwarded by
# docker-compose.yml so NAT'd RTP packets actually reach asterisk.
# Asterisk's stock rtp.conf defaults to 10000-20000, but docker-compose
# only forwards 10000-10100. RTP allocated outside the forward range
# means the call is silent (no audio in either direction).
cat > /etc/asterisk/rtp.conf <<RTP
[general]
rtpstart=10000
rtpend=10100
strictrtp=yes
RTP

cat > /etc/asterisk/manager.conf <<MGR
[general]
enabled=yes
port=5038
bindaddr=127.0.0.1

[astradial]
secret=${ASTERISK_AMI_SECRET:-astradial}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.0/255.255.255.0
read=system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate
write=system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate
MGR

# Developer-mode trunk — pre-wires a registration to a remote Astradial
# Cloud SIP server. Only used when both env vars are present.
if [ "${ASTRADIAL_MODE:-}" = "developer" ] && [ -n "${ASTRADIAL_TRUNK_HOST:-}" ]; then
  echo "Developer mode: configuring trunk to ${ASTRADIAL_TRUNK_HOST}..."
  cat > /etc/asterisk/pjsip_astradial_cloud.conf <<EOF
[astradial-cloud]
type=registration
server_uri=sip:${ASTRADIAL_TRUNK_HOST}:5060
client_uri=sip:${ASTRADIAL_TRUNK_USER}@${ASTRADIAL_TRUNK_HOST}
outbound_auth=astradial-cloud-auth
retry_interval=60
expiration=3600

[astradial-cloud-auth]
type=auth
auth_type=userpass
username=${ASTRADIAL_TRUNK_USER}
password=${ASTRADIAL_TRUNK_PASS}

[astradial-cloud-endpoint]
type=endpoint
context=from-astradial-cloud
transport=transport-udp
auth=astradial-cloud-auth
aors=astradial-cloud-aor
disallow=all
allow=ulaw,alaw,g722
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
direct_media=no

[astradial-cloud-aor]
type=aor
contact=sip:${ASTRADIAL_TRUNK_HOST}:5060
qualify_frequency=30
EOF
  if ! grep -q "pjsip_astradial_cloud.conf" /etc/asterisk/pjsip.conf 2>/dev/null; then
    echo "#include pjsip_astradial_cloud.conf" >> /etc/asterisk/pjsip.conf
  fi
fi

############################################################################
# 2. Wait for mariadb
############################################################################
echo "Waiting for database..."
for i in $(seq 1 30); do
  if node -e "
    const m = require('mariadb');
    const p = m.createPool({host:process.env.DB_HOST||'localhost',port:parseInt(process.env.DB_PORT)||3306,user:process.env.DB_USER||'astradial',password:process.env.DB_PASSWORD||'changeme',database:process.env.DB_NAME||'astradial',connectionLimit:1});
    p.getConnection().then(c=>{c.release();p.end();console.log('DB ready');process.exit(0)}).catch(()=>process.exit(1));
  " 2>/dev/null; then
    break
  fi
  echo "  attempt $i/30..."
  sleep 2
done

############################################################################
# 3. Schema bootstrap + admin seed
############################################################################
echo "Bootstrapping schema..."
node scripts/bootstrap-or-migrate.js

echo "Checking seed..."
node seed.js || true

############################################################################
# 4. Run asterisk + node under supervisord
############################################################################
echo "Starting supervisord (asterisk + api)..."
exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
