const fs = require('fs').promises;
const path = require('path');
const AsteriskManager = require('../asterisk/asteriskManager');

/**
 * Deployment Service
 * Handles deployment of global settings to Asterisk via configuration files and AMI
 */
class DeploymentService {

  constructor() {
    this.asteriskManager = new AsteriskManager();
    this.configBasePath = process.env.ASTERISK_CONFIG_PATH || '/etc/asterisk';
  }

  /**
   * Deploy global settings to Asterisk
   * Generates configuration files and reloads/restarts Asterisk
   * @param {Object} settings - Global settings object
   * @param {Object} options - Deployment options
   * @param {boolean} options.restart - If true, restart Asterisk instead of reload (default: false)
   */
  async deployGlobalSettings(settings, options = {}) {
    const { restart = false } = options;

    const results = {
      pjsip_transport: null,
      rtp: null,
      sip_global: null,
      voicemail: null,
      reload_results: [],
      restart_performed: false
    };

    try {
      // Generate PJSIP transport configuration
      if (settings.pjsip_transport) {
        results.pjsip_transport = await this.deployPJSIPTransport(settings.pjsip_transport);
      }

      // Generate RTP configuration
      if (settings.rtp_config) {
        results.rtp = await this.deployRTPConfig(settings.rtp_config);
      }

      // Generate SIP global settings
      if (settings.sip_global) {
        results.sip_global = await this.deploySIPGlobal(settings.sip_global, settings.codecs);
      }

      // Deploy voicemail configuration
      if (settings.voicemail) {
        results.voicemail = await this.deployVoicemailConfig(settings.voicemail);
      }

      await this.asteriskManager.connect();

      // RESTART: Full Asterisk restart (affects all tenants)
      if (restart) {
        console.log('🔄 Restarting Asterisk (affects all organizations)...');
        try {
          const restartResult = await this.asteriskManager.restartAsterisk();
          results.restart_performed = true;
          results.reload_results.push({
            action: 'restart',
            success: true,
            response: restartResult,
            warning: 'Full Asterisk restart performed - affects all organizations'
          });
        } catch (error) {
          results.reload_results.push({
            action: 'restart',
            success: false,
            error: error.message
          });
          throw new Error(`Asterisk restart failed: ${error.message}`);
        }
      }
      // RELOAD: Module-specific reload only (minimal disruption)
      else {
        // Reload PJSIP
        if (results.pjsip_transport || results.sip_global) {
          try {
            const pjsipReload = await this.asteriskManager.reloadModule('res_pjsip.so');
            results.reload_results.push({ module: 'res_pjsip.so', success: true, response: pjsipReload });
          } catch (error) {
            results.reload_results.push({ module: 'res_pjsip.so', success: false, error: error.message });
          }
        }

        // Reload RTP
        if (results.rtp) {
          try {
            const rtpReload = await this.asteriskManager.reloadModule('res_rtp_asterisk.so');
            results.reload_results.push({ module: 'res_rtp_asterisk.so', success: true, response: rtpReload });
          } catch (error) {
            results.reload_results.push({ module: 'res_rtp_asterisk.so', success: false, error: error.message });
          }
        }

        // Reload voicemail
        if (results.voicemail) {
          try {
            const vmReload = await this.asteriskManager.reloadModule('app_voicemail.so');
            results.reload_results.push({ module: 'app_voicemail.so', success: true, response: vmReload });
          } catch (error) {
            results.reload_results.push({ module: 'app_voicemail.so', success: false, error: error.message });
          }
        }
      }

      await this.asteriskManager.disconnect();

      return {
        success: true,
        message: restart ? 'Global settings deployed with full Asterisk restart' : 'Global settings deployed with module reload',
        results
      };

    } catch (error) {
      console.error('❌ Deployment error:', error);
      throw new Error(`Failed to deploy global settings: ${error.message}`);
    }
  }

  /**
   * Deploy PJSIP transport configuration
   */
  async deployPJSIPTransport(transportConfig) {
    let config = '; PJSIP Transport Configuration\n';
    config += '; Auto-generated by PBX API\n\n';

    // UDP Transport
    if (transportConfig.udp && transportConfig.udp.enabled) {
      config += '[transport-udp]\n';
      config += 'type=transport\n';
      config += 'protocol=udp\n';
      config += `bind=${transportConfig.udp.bind}\n`;

      if (transportConfig.udp.external_media_address) {
        config += `external_media_address=${transportConfig.udp.external_media_address}\n`;
      }

      if (transportConfig.udp.external_signaling_address) {
        config += `external_signaling_address=${transportConfig.udp.external_signaling_address}\n`;
      }

      if (transportConfig.udp.local_net && Array.isArray(transportConfig.udp.local_net)) {
        transportConfig.udp.local_net.forEach(net => {
          config += `local_net=${net}\n`;
        });
      }

      config += '\n';
    }

    // TCP Transport
    if (transportConfig.tcp && transportConfig.tcp.enabled) {
      config += '[transport-tcp]\n';
      config += 'type=transport\n';
      config += 'protocol=tcp\n';
      config += `bind=${transportConfig.tcp.bind}\n\n`;
    }

    // TLS Transport
    if (transportConfig.tls && transportConfig.tls.enabled) {
      config += '[transport-tls]\n';
      config += 'type=transport\n';
      config += 'protocol=tls\n';
      config += `bind=${transportConfig.tls.bind}\n`;

      if (transportConfig.tls.cert_file) {
        config += `cert_file=${transportConfig.tls.cert_file}\n`;
      }

      if (transportConfig.tls.privkey_file) {
        config += `priv_key_file=${transportConfig.tls.privkey_file}\n`;
      }

      if (transportConfig.tls.cipher) {
        config += `cipher=${transportConfig.tls.cipher}\n`;
      }

      if (transportConfig.tls.method) {
        config += `method=${transportConfig.tls.method}\n`;
      }

      config += '\n';
    }

    // WSS Transport (WebRTC)
    if (transportConfig.wss && transportConfig.wss.enabled) {
      config += '[transport-wss]\n';
      config += 'type=transport\n';
      config += 'protocol=wss\n';
      config += `bind=${transportConfig.wss.bind}\n`;

      if (transportConfig.wss.cert_file) {
        config += `cert_file=${transportConfig.wss.cert_file}\n`;
      }

      if (transportConfig.wss.privkey_file) {
        config += `priv_key_file=${transportConfig.wss.privkey_file}\n`;
      }

      config += '\n';
    }

    // Write configuration file
    const configPath = path.join(this.configBasePath, 'pjsip_transport.conf');
    await fs.writeFile(configPath, config, 'utf8');

    return {
      success: true,
      file: configPath,
      content: config
    };
  }

  /**
   * Deploy RTP configuration
   */
  async deployRTPConfig(rtpConfig) {
    let config = '; RTP Configuration\n';
    config += '; Auto-generated by PBX API\n\n';
    config += '[general]\n';
    config += `rtpstart=${rtpConfig.rtp_start || 10000}\n`;
    config += `rtpend=${rtpConfig.rtp_end || 20000}\n`;
    config += `rtcpmux=${rtpConfig.rtcp_mux ? 'yes' : 'no'}\n`;
    config += `icesupport=${rtpConfig.ice_support ? 'yes' : 'no'}\n`;

    if (rtpConfig.stun_server) {
      config += `stunaddr=${rtpConfig.stun_server}\n`;
    }

    if (rtpConfig.turn_server) {
      config += `turnaddr=${rtpConfig.turn_server}\n`;
    }

    config += '\n';

    // Write configuration file
    const configPath = path.join(this.configBasePath, 'rtp.conf');
    await fs.writeFile(configPath, config, 'utf8');

    return {
      success: true,
      file: configPath,
      content: config
    };
  }

  /**
   * Deploy SIP global settings and codecs
   */
  async deploySIPGlobal(sipGlobal, codecs) {
    let config = '; SIP Global Settings\n';
    config += '; Auto-generated by PBX API\n\n';
    config += '[global]\n';
    config += 'type=global\n';

    if (sipGlobal.user_agent) {
      config += `user_agent=${sipGlobal.user_agent}\n`;
    }

    if (sipGlobal.default_expiry) {
      config += `default_expiry=${sipGlobal.default_expiry}\n`;
    }

    if (sipGlobal.min_expiry) {
      config += `min_expiry=${sipGlobal.min_expiry}\n`;
    }

    if (sipGlobal.max_expiry) {
      config += `max_expiry=${sipGlobal.max_expiry}\n`;
    }

    config += `mwi_disable_initial_unsolicited=${sipGlobal.mwi_disable_initial_unsolicited ? 'yes' : 'no'}\n`;
    config += `ignore_uri_user_options=${sipGlobal.ignore_uri_user_options ? 'yes' : 'no'}\n`;
    config += `send_rpid=${sipGlobal.send_rpid ? 'yes' : 'no'}\n`;
    config += '\n';

    // Add codec preferences if provided
    if (codecs) {
      config += '; Codec Configuration\n';

      if (codecs.disallow) {
        config += `disallow=${codecs.disallow}\n`;
      }

      if (codecs.allow && Array.isArray(codecs.allow)) {
        codecs.allow.forEach(codec => {
          config += `allow=${codec}\n`;
        });
      }

      config += '\n';
    }

    // Write configuration file
    const configPath = path.join(this.configBasePath, 'pjsip_global.conf');
    await fs.writeFile(configPath, config, 'utf8');

    return {
      success: true,
      file: configPath,
      content: config
    };
  }

  /**
   * Deploy voicemail configuration
   */
  async deployVoicemailConfig(vmConfig) {
    let config = '; Voicemail Configuration\n';
    config += '; Auto-generated by PBX API\n\n';
    config += '[general]\n';
    config += `maxmsg=${vmConfig.max_messages || 100}\n`;
    config += `maxsecs=${vmConfig.max_msg_duration || 180}\n`;
    config += `minsecs=${vmConfig.min_msg_duration || 2}\n`;
    config += `emaildateformat=%A, %B %d, %Y at %r\n`;

    if (vmConfig.email_notifications) {
      config += 'attach=yes\n';
      config += 'emailbody=Dear ${VM_NAME}:\n\n\tJust wanted to let you know you were just left a ${VM_DUR} long message (number ${VM_MSGNUM})\n\tin mailbox ${VM_MAILBOX} from ${VM_CALLERID}, on ${VM_DATE}.\n\n';
    } else {
      config += 'attach=no\n';
    }

    config += '\n';

    const configPath = path.join(this.configBasePath, 'voicemail.conf');
    await fs.writeFile(configPath, config, 'utf8');

    return {
      success: true,
      file: configPath,
      content: config
    };
  }
}

module.exports = new DeploymentService();
